### ISSUE TITLE
Cannot Import tpot

### ISSUE THREAD

**Issue by dhanush-ai1990** [llSourcell/genetic_algorithm_challenge#5]
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_mnist_pipeline.py')

Error:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from tpot import TPOTClassifier
ModuleNotFoundError: No module named 'tpot'

Pip3 list shows tpot installed

skrebate (0.4)
spacy (1.8.0)
stopit (1.1.1)
tensorflow (1.2.1)
termcolor (1.1.0)
thinc (6.5.2)
toolz (0.8.2)
TPOT (0.9.2)
tqdm (4.19.4)
ujson (1.35)
update-checker (0.16)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.30.0)
wrapt (1.10.11)

This is mac OS

**Comment by dhanush987** [comment]
I installed tpot for python2 as pip install tpot and it works fine. I am not sure why it is not working for python3

**Comment by dhanush-ai1990** [comment]
I posted this under tpot. Got the wrong repository
